- name: Frontend Setup
  hosts: all
  become: yes
  tasks:
    - name: Installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Start Nginx
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx