- name: Get secrets
  hosts: localhost
  vars:
    ssh: "{{ lookup('hashi_vault', 'secret=common/data/ssh token=AES:SwJnjN2xu5okR7QrKc6/6Q==:8fYPWT/nNBNEjm0So1OXTL9nXRM/dfSTdyGgTzj9pII= url=https:///vault.akhilsaidevops.online:8200 validate_certs=False')}}"
  tasks:
    - name: create secrets file
      ansible.builtin.lineinfile:
        path: secrets.json
        line: "{{ssh}}"
        create: yes