- name: Get secrets
  hosts: localhost
  tasks:
    - name: create file
      ansible.builtin.lineinfile:
        path: /tmp/test
        line: "username: {{ lookup('hashi_vault', 'secret=common/data/ssh token=AES:SwJnjN2xu5okR7QrKc6/6Q==:8fYPWT/nNBNEjm0So1OXTL9nXRM/dfSTdyGgTzj9pII= url=https:///vault.akhilsaidevops.online:8200 validate_certs=False')}}"
        create: yes