- name: Get secrets
  hosts: localhost
  vars:
    ssh: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.akhilsaidevops.online:8200 validate_certs=False')}}"
  tasks:
    - name: create secrets file
      ansible.builtin.lineinfile:
        path: secrets.json
        line: "{{ssh}}"
        create: yes