- name: Clean the old content
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory
    owner: "{{app_user}}"
    group: "{{app_user}}"

#- name: Download and Extract app content
#  ansible.builtin.unarchive:
#    src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
#    dest: "{{ app_loc }}"
#    remote_src: yes
#    owner: "{{app_user}}"
#    group: "{{app_user}}"

- name: Download and Extract app content - from Artifactory
  ansible.builtin.unarchive:
    src: http://{{artifactory_user}}:{{artifactory_password}}@artifactory-internal.akhilsaidevops.online:8081/artifactory/expense-{{ component }}/{{APP_VERSION}}.zip
    dest: "{{ app_loc }}"
    remote_src: yes
    owner: "{{app_user}}"
    group: "{{app_user}}"